Fix incompatibility issue of ``UserPasswordAuth`` with python 3.
