Make :py:class:`future.moves.urllib.error.URLError` available in
:py:module:`buildbot_net_usage_data` module.  Fixes an exception found in
:py:function:`buildbot_net_usage_data._sendWithUrlib` when running through the
tutorial using Python 3.
